### ISSUE TITLE
Call from Twilio gives a spoken error message

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#118]
"I'm sorry, an application error has occurred"

From www.takeyourmeds.co.uk

**Comment by DeckOfPandas** [comment]
Twilio log: 
Error 12100: Twilio was unable to parse the provided XML Document. (etc)

**Comment by DeckOfPandas** [comment]
--> View Call shows:

"Error on line 2 of document  : The processing instruction target matching "[xX][mM][lL]" is not allowed.  Please ensure that the response body is a valid XML document."

**Comment by DeckOfPandas** [comment]
I can't fix this problem.

The XML has
<Play loop="1">/static/mp3/hi_mum_medication_reminder.mp3</Play>
in place of
<Play loop="1">/media/mp3/hi_mum_medication_reminder.mp3</Play>

But I can't work out where this string is built.

I ended up at:
    if reminder.audio_url:
        make_call(
            reminder.phone_number,
            staticfiles_storage.url(reminder.audio_url),
        )
        return

./takeyourmeds/settings/defaults/**init**.py has:
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'media'),)
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

...and then I'm stuck.

@lamby : Could this be added on to milestone 3 please? Apologies, I don't know what else to do, and the app currently doesn't work...

**Comment by lamby** [comment]
This was two separate problems:
- `the processing instruction target matching "[xX][mM][lL]"` was due to leading whitespace fixed in eebd831f46b5b4ea723e2aed7d72a1311368462c
- I'm not sure why you thought there was an issue with `/static` vs `/media`, but the real problem here was a lack of absolute url prefix, ie. `http://www.takeyourmeds.co.uk/static`. A good example of why ""Describe the goal, not the step" is in the Smart Questions FAQ :)   Fixed in 37d8f1c95df74282c8fe0bca511a9f34a522f30b

(I can receive SMS whilst abroad but I can't appear to receive phone calls on my number. The twilio logs do suggest it is now working, however.)
