### ISSUE TITLE
End-user signup process

### ISSUE THREAD

**Issue by lamby** [takeyourmeds/takeyourmeds-web#129]

**Comment by DeckOfPandas** [comment]
Tagging @lamby and @pacharanero here.
Please tell me what you think.

MODEL OPTION 0:
1. TYM generates a "Practice ID" for a GP practice or dental surgery or whatever
1. TYM generates a list of 8-char strings of lowercase letters for each Practice ID and stores these in a database, called "Access tokens" or similar
2. Practice ID and Access Token are given to patients via their GP practice, which, at the start, will be Helen giving patients a piece of paper with instructions on (mirroring current model for patients registering for online GP services).
3. Patient goes to takeyourmeds.co.uk/register, and sees textfields:
   Email address: ______________
   Choose a password: _________
   Practice ID: ________________ (optional)
   Access token: ______________ (optional)
4. Access token is checked against database and Practice ID

STORIES:
1. Patient has a piece of paper with clear instructions (written by Helen)
2. TYM has a database of Practice ID, Access Token, and Boolean for whether signed up or not
3. GP gives patient a piece of paper and stores no data

ADVANTAGES:
- Nothing is required from the practice to get started
- Piece of paper can be given to a relative to sign up on behalf of the patient, and we're already targeting this low-tech market
- TYM can easily tell a practice how many of their registered patients have signed up for TYM
- TYM doesn't hold any patient-identifiable information
- ...?

DISADVANTAGES:
- Doesn't scale for the future, when it would be ideal if signed-up GP practices could generate their own access tokens (BUT we don't need to do this so-called "futureproofing" of a new feature now, as previosuly discussed with @lamby 
- GP practice has to ask TYM for usage data
- ...?

**Comment by lamby** [comment]
Braindumping:
- Don't see the justification for separate access tokens especially when they are clearly going to be a load of faff. ie. why we need to uniquely identify the user? Don't we just care which practice ID they are associated with?
- Why are the fields optional? Anything "nullable" is almost always a bad idea as it introduces extra state into our mental model. I see "Nothing is required from the practice to get started", but that seems like a feature entirely orthogonal to this and not a specific advantage of this solution.

Hell, do we even need practice IDs and any magic tokens? We can just have a drop-down with all the active practices.

**Comment by DeckOfPandas** [comment]
Braindumped responses:

It would be useful to be able to uniquely identify the user for audit
purposes. That's a bit wishy-washy I know, but
thinking it through it seems that it would be hard to identify users
retroactively after signup. CCGs are likely to require user-level (albeit
anonymised) data in order to justify the cost.

I thought those signup fields should be optional to allow users to sign up
outside of a practice/CCG and hence to pay individually through the Stripe
subscription. We need to plan for this as well as the CCG model because the
latter is likely to be slow to get going and slow to implement.

The concern with the practice/CCG dropdown is then that theoretically
anyone could sign up, sapping our money and requiring us to overcharge
paying groups to cover freeloaders. This is unlikely to add up to much
money I suppose, but that approach totally doesn't scale.

**Comment by DeckOfPandas** [comment]
Basically I think that we need to generate Access Tokens and verify them at
signup, but that we don't need a Practice ID separately. An individual user
doesn't care which group they're in -- a user list would be a property of
the group paying for the service .

**Comment by lamby** [comment]
> we need to generate Access Tokens and verify them at signup, but that we don't need a Practice ID separately

(That's true; each token would imply a practice ID.)

What's yet to be documented I think is:
- How you want to generate access tokens - eg. "generate me X, store them against this particular practice and then show me them so I guess I can print / email them"
- How the non-access token signup works, etc. Should we just assign them to the "no practice Practice" for now?

**Comment by DeckOfPandas** [comment]
How I will need to use the Access Tokens:
- I'll need to do some mailmerge wizardry to automagically print the codes
  on to registration letters, so the database needs to be exportable to e.g.
  Excel/Google sheets

My internal version of such a database looks like this:
User (key) | Group ID | Access Token

I suspect we shouldn't use Excel to generate the codes as that wouldn't be
"secure" -- in inverted commas because security isn't really the issue, but
I'd still prefer some non-Excel algorithmic way of generating 8-char strings
- Yes, if no code, assign to 00000000 or whatever
- I think Access Tokens should use just lowercase letters to avoid that
  stupid ambiguity of "Is this an I or a 1"

**Comment by lamby** [comment]
> My internal version of such a database looks like this:
> User (key) | Group ID | Access Token

What's "user" here? They haven't registered yet by definition, so there is no user to store when the access token is generated - ie. do you mean this to be nullable?

> I suspect we shouldn't use Excel to generate the codes

Hm. I was assuming all along that the TakeYourMeds site would generate the codes, as it needs to store them anyway to associate later..  Needing to make them in Excel and then upload them seems unnecessary faff.

> - Yes, if no code, assign to 00000000 or whatever

I don't follow, sorry. Do you recall our previous conversations about having a "null" practice/groups? My question, in that context, is would we just assign the users to that group?

> I think Access Tokens should use just lowercase letters to avoid that stupid ambiguity of "Is this an I or a 1"

Upper-case is, in general, far more readable :)  But the typical nice-to-the-user solution here is to a) simply not include "I" and "O" in this alphabet and accept both upper/lower/mixed versions.
- What happens if the access token has already been used

**Comment by DeckOfPandas** [comment]
1. That was the database after the user had signed up. When the Tokens are
   generated, yes, the user would be null, as the Token hasn't been assigned
   yet.
2. (Did you misread "should" for "shouldn't"?)
3. Yes, you're right, assign to the null group.
4. Yes, fine, uppercase and no I/O
5. If the token has already been used, display an error message like when
   e.g. password isn't entered: "This access token has already been used" or
   similar (screenshot below)

![screenshot](https://cloud.githubusercontent.com/assets/2399432/11419169/7e3d16d6-941d-11e5-808b-10afa1ab3831.png)

**Comment by lamby** [comment]
Cool. I think I have enough to get going here.

>  display an error message like when e.g. password isn't entered: "This access token has already been used" or similar (screenshot below)

Just FYI those are HTML5 frontend validation errors; don't think we can actually use them. Anyway, display an error rather than let them through, etc.

**Comment by DeckOfPandas** [comment]
Ohh, I assumed they was an Assan thing as they're quite nice-looking! But
yes, thanks :)

**Comment by lamby** [comment]
This is now live. You'll need to:
- Make yourself a superuser by running `UPDATE account_user SET is_superuser = true WHERE email = 'helen@deckofpandas.co.uk';`  on each server
- Browse to `/admin`

(Hey, you should test my database access instructions, right?)
