### ISSUE TITLE
Stripe integration with parent "account" entity

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#45]

**Comment by lamby** [comment]
So it's a little unclear what the on → off transition would imply. If this means not charging existing users, then that would require poking Stripe if they already have billing setup, and then re-enabling them when this is goes off → on, etc. etc. And a bunch of other edge cases that I'm sure we would miss. Basically almost guaranteed to have a big mess that'll be a pain to fix because it's in Stripe, etc.

If the goal is for us to disable payments _now_ whilst drumming-up business (!) and experimenting, and then enabling payments later, then that's a different and altogether simpler proposition.

Another sensible alternative that I've previously employed is simply to have payments always enabled with no toggle, but crucially have a "free forever" plan that can be a) disabled later, b) upgraded _from_ once in the steady state.

**Comment by lamby** [comment]
> payments always enabled with no toggle

(On phone: going with this)

**Comment by lamby** [comment]
NB. A stripe _customer_ will not a Django `auth.User` -- we will be charging people at a level "above" this.

**Comment by lamby** [comment]
(I wonder if this needs to be part of this milestone, especially the "parent" bit. I suspect so.)

**Comment by lamby** [comment]
Assuming group noun:
- group model
- profile userdata to store user's group association
- add a free plan on stripe
- "no group" group for these initial users, ensure no group is a member of this
- group links to stripe

**Comment by lamby** [comment]
WIP in https://github.com/takeyourmeds/takeyourmeds-web/compare/83ce4d6b77c702699e4dfbdd163274c10412ad82...4f12e14fcaaff75411059427d089d053869fdfcc

**Comment by lamby** [comment]
just need to do the stripe bit now

**Comment by lamby** [comment]
Done, just need to have the stripe configuration on stage/live.

**Comment by lamby** [comment]
Done
